export * from 'framer-motion/dom'
export { motionValue as useMotionValue } from 'framer-motion/dom'
export { default as Motion, type MotionProps } from './components/Motion.vue'
export { default as AnimatePresence, type AnimatePresenceProps } from './components/AnimatePresence.vue'
export * from './value'
