export * from 'framer-motion/dom'
export { motionValue as useMotionValue } from 'framer-motion/dom'
export { default as Motion, type MotionProps } from './components/Motion.vue'
export { default as AnimatePresence } from './components/AnimatePresence.vue'
export type { AnimatePresenceProps } from './components/type'
export { default as LayoutGroup } from './components/LayoutGroup.vue'
export { useLayoutGroup } from './components/use-layout-group'
export type { LayoutGroupProps } from './components/use-layout-group'
export * from './components/motion-config'
export * from './components/context'
export * from './value'
export * from './constants'
export * from './types'
export * from './animation'
export * from './utils'
export type { PanInfo } from './features/gestures/pan/PanSession'
