export * from 'framer-motion/dom'
export { motionValue as useMotionValue } from 'framer-motion/dom'
export { default as Motion, type MotionProps } from './components/Motion.vue'
export { default as AnimatePresence, type AnimatePresenceProps } from './components/AnimatePresence.vue'
export { default as LayoutGroup, type LayoutGroupProps } from './components/LayoutGroup.vue'
export * from './components/context'
export * from './value'
export * from './constants'
export type { Variant, Options } from './types'
export * from './animation'
export * from './utils'
